config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations
  
  authenticate :user, lambda { |u| u.gerente? } do
    resources :users # Assumindo que você tem uma forma de criar usuários que não é o sign-up do Devise
  end
  
  resources :items
  
  resources :inventories
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
    has_one :inventory

    accepts_nested_attributes_for :inventory
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: %i[ atendente gerente ]
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: %i[ show edit update destroy ]

  # GET /inventories or /inventories.json
  def index
    @inventories = Inventory.all
  end

  # GET /inventories/1 or /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories or /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to inventory_url(@inventory), notice: "Inventory was successfully created." }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1 or /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to inventory_url(@inventory), notice: "Inventory was successfully updated." }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1 or /inventories/1.json
  def destroy
    @inventory.destroy

    respond_to do |format|
      format.html { redirect_to inventories_url, notice: "Inventory was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inventory_params
      params.require(:inventory).permit(:item_id, :quantity)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
    @item.build_inventory
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, :price, :active, inventory_attributes: [:quantity])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        # format.html { redirect_to user_url(@user), notice: "user was successfully created." }
        format.html { redirect_to users_url, notice: "user was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def show
  end

  private 
  
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :role, :active)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/default_helper.rb
module DefaultHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def ativo?(ativo)
        if ativo 
            'text-success'
        else
            'text-danger'
        end
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/inventories/_form.html.erb
<%= form_with(model: inventory) do |form| %>
  <% if inventory.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
        <% inventory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-12 p-2">
      <%= form.label :item_id, class: 'form-label' %>
      <%= form.select :item_id, Item.all.map {|i| [i.title.capitalize, i.id]}, {}, class: 'form-select' %>
    </div>

    <div class="col-12 p-2">
      <%= form.label :quantity, class: 'form-label' %>
      <%= form.number_field :quantity, class: 'form-control' %>
    </div>

    <div class="col-12 p-2">
     <%= form.submit 'Cadastrar', class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/inventories/_inventory.html.erb
<div id="<%= dom_id inventory %>">
  <p>
    <strong>Item:</strong>
    <%= inventory.item_id %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= inventory.quantity %>
  </p>

</div>

app/views/inventories/edit.html.erb
<h1>Editing inventory</h1>

<%= render "form", inventory: @inventory %>

<br>

<div>
  <%= link_to "Show this inventory", @inventory %> |
  <%= link_to "Back to inventories", inventories_path %>
</div>

app/views/inventories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Inventories</h1>

<div id="inventories">
  <% @inventories.each do |inventory| %>
    <%= render inventory %>
    <p>
      <%= link_to "Show this inventory", inventory %>
    </p>
  <% end %>
</div>

<%= link_to "New inventory", new_inventory_path %>

app/views/inventories/new.html.erb
<h1>New inventory</h1>

<%= render "form", inventory: @inventory %>

<br>

<div>
  <%= link_to "Back to inventories", inventories_path %>
</div>

app/views/inventories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @inventory %>

<div>
  <%= link_to "Edit this inventory", edit_inventory_path(@inventory) %> |
  <%= link_to "Back to inventories", inventories_path %>

  <%= button_to "Destroy this inventory", @inventory, method: :delete %>
</div>

app/views/items/_form.html.erb
<div class="container mt-5">
  <%= form_with(model: item) do |form| %>
    <% if item.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

        <ul>
          <% item.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="col-12 p-2">
        <%= form.label :title, class: 'form-label' %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="col-12 p-2">
        <%= form.label :price, class: 'form-label' %>
        <%= form.text_field :price, class: 'form-control' %>
      </div>


      <!--
        Dados de Inventory
      -->
      <%= form.fields_for :inventory do |inventory_form| %>
        <div class="field">
          <%= inventory_form.label :quantity, class: 'form-label' %>
          <%= inventory_form.number_field :quantity, id: :inventory_quantity, class: 'form-control' %>
        </div>
      <% end %>
      <!--
        Fim
      -->

      <div class="col-12 p-2">
        <%= form.check_box :active, class: 'form-check-input' %>
        <%= form.label :active, class: 'form-check-label' %>
      </div>


      <div class="col-12 p-2">
        <%= form.submit 'Criar produto', class: 'btn btn-success' %>
      </div>
    </div>
  <% end %>
</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
<h1>Items</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Titulo</th>
      <th scope="col">Preço</th>
      <th scope="col" class="text-center">Ativo?</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <th scope="row"><%= item.id %></th>
        <td><%= link_to item.title, item, class: 'nav-link' %></td>
        <td>R$<%= item.price %>,00</td>
        <td class="text-center"><i class="bi bi-circle-fill <%= ativo?(item.active)%>"></i></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New item", new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-6">
        
        <h5 class="card-title align-middle">
          <%= link_to items_path, class: 'btn btn-outline-white' do %>
            <i class="bi bi-arrow-left"></i>
          <% end %>         
          <%= @item.title %></h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      </div>
      <div class="col-6">
        <div class="d-flex">
          <%= link_to edit_item_path(@item), class: 'btn btn-warning m-1' do %>
            <i class="bi bi-pencil"></i>
          <% end %>
          
          <%= button_to @item, method: :delete, class: 'btn btn-danger m-1' do %>
            <i class="bi bi-trash"></i>
          <% end %>
        </div>
      </div>

    </div>      
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormularioAninhado</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if user_signed_in? %>
      <% if current_user.active %>
        <div class="row">
          <div class="col-3">
            <%= render 'shared/navbar' %>

          </div>
          <div class="col-9">
            <div class="container mt-5">
              <%= yield %>
            </div>
          </div>
        </div>
      <% else %>
        <h1>Aguarde a ativação do seu usuário</h1>
        <%= button_to 'Sair', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
      <% end %>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="d-flex flex-column flex-shrink-0 p-3 bg-body-tertiary w-100" style="height: 100vh;">
    <%= link_to root_path, class: 'd-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none' do %>
        <i class="bi bi-bootstrap pe-none me-2 fs-4"></i>
        <span class="fs-4">
            Sidebar
        </span>
    <% end %>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <%= link_to root_path, class: 'nav-link link-body-emphasis' do %>
            <i class="bi bi-speedometer2 pe-none me-2"></i>
            Dashboard
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to inventories_path, class: 'nav-link link-body-emphasis' do %>
            <i class="bi bi-table pe-none me-2"></i>
            Estoque
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to root_path, class: 'nav-link link-body-emphasis' do %>
            <i class="bi bi-grid pe-none me-2"></i>
            Produtos
        <% end %>
      </li>
      <% if current_user.gerente?%>
      <li class="nav-item">
        <%= link_to users_path, class: 'nav-link link-body-emphasis' do %>
            <i class="bi bi-person-circle pe-none me-2"></i>
            Usuários
        <% end %>
      </li>
      <% end %>
    </ul>
    <hr>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
        <strong><%= current_user.email %></strong>
      </a>
      <ul class="dropdown-menu text-small shadow">
        <li><a class="dropdown-item" href="#">Profile</a></li>
        <li><hr class="dropdown-divider"></li>
        <li>
            <%= button_to 'Sair', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
        </li>
      </ul>
    </div>
  </div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-12 p-2">
      <%= form.label :email, class: 'form-label' %>
      <%= form.email_field :email, class: 'form-control' %>
    </div>

    <div class="col-12 p-2">
      <%= form.label :password, class: 'form-label' %>
      <%= form.password_field :password, class: 'form-control' %>
    </div>


    <div class="col-12 p-2">
      <%= form.label :password_confirmation, class: 'form-label' %>
      <%= form.password_field :password_confirmation, class: 'form-control' %>
    </div>

    <div class="col-12 p-2">
      <%= form.label :active, class: 'form-label' %>
      <%= form.check_box :active, class: 'form-checkbox' %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  </div>

<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Usuários</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Email</th>
      <th scope="col">Perfil</th>
      <th scope="col" class="text-center">Ativo?</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <th scope="row"><%= user.id %></th>
        <td><%= user.email %></td>
        <td><%= user.role.capitalize %></td>
        <td class="text-center"><i class="bi bi-circle-fill <%= ativo?(user.active)%>"></i></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>